@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant ":FindMatchType" as FindMatchType LOGIC_COLOR
participant "p:PersonPredicate" as PersonPredicate LOGIC_COLOR
participant "f:FindCommand" as FindCommand LOGIC_COLOR
end box

[-> LogicManager : execute("find ...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("find ...")
activate AddressBookParser

create FindCommandParser
AddressBookParser -> FindCommandParser
activate FindCommandParser

FindCommandParser -> FindCommandParser : parseFindArgs()
activate FindCommandParser
alt m/ prefix provided
    FindCommandParser -> ParserUtil : tokenizeSpaceSeparated()
    FindCommandParser -> FindMatchType : fromToken()
    FindMatchType --> FindCommandParser : matchType
    FindCommandParser -> FindCommandParser : build ParsedFindArgs()
else m/ prefix not provided
    FindCommandParser -> ParserUtil : tokenizeSpaceSeparated()
    FindCommandParser -> FindCommandParser : build ParsedFindArgs()
end
deactivate FindCommandParser

FindCommandParser -> FindCommandParser : ensure keywords not empty
FindCommandParser -> FindMatchType : createPredicate()
activate FindMatchType
create PersonPredicate
FindMatchType -> PersonPredicate
FindMatchType --> FindCommandParser : p
deactivate FindMatchType

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand
FindCommand --> FindCommandParser : f
deactivate FindCommand

FindCommandParser --> AddressBookParser : f
deactivate FindCommandParser
FindCommandParser -[hidden]-> AddressBookParser
destroy FindCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

[<--LogicManager
deactivate LogicManager
@enduml
